dist: xenial

language: python

sudo: false

branches:
  only:
    - master

python:
  - 3.6
  - 3.7

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37

install:
  pip install tox numpy scipy scikit-learn matplotlib seaborn

script:
  tox &&
  pip install git+https://github.com/chlorochrule/cknn
