dist: xenial

language: python

sudo: false

branches:
    only:
        - master

python:
    - 3.5
    - 3.6
    - 3.7

install:
    pip install numpy scipy scikit-learn matplotlib seaborn

script:
    python setup.py test
    pip install pip install git+https://github.com/chlorochrule/cknn
