language: python
os: linux
dist: xenial
branches:
  only:
  - master
env:
  global:
    secure: tvfUP60xgdgWQPQx+/wI9iIlV9rxQRy2JXvdK/L/uSmwACK/KwKLu6vaaD1X2L8KEcecPrnzQNjER0Trwn/uS7pj7sMbH25keJFj1RGEu3BR1vkVVceRntqpyom62gN4gG8NPuNR+zvfayR+UQSrVxc5/hk9xZ0PnTwoavkO3SJpsoYNEyVLYvSBQqagyBAECN14JQQYcn+Qt9VfAdvSQTnsLtr/VTOjXDkjkZES4jBRBj/L4WJ7chAkS0zYZ2UT06DUc+6rCz6BEvnvryTjJh/vrWFNI0/O8YbZZHuSHeF0ygp1LvqPj4/OXHENDWqDxST+RtJiV+2yqBlk3+57b3Mo6J9RCgu0MPWSx6yXsHPWHCS42FudJJvW86xyqJAzBeUuNJk1S7HfGePmOimnWyZSGmuWWG1DvNyPMqskb7De9+zqj1cSKwM5Th8QfF+KsO/JD5l0To5U+EyEgMYTS8bCc7jZMPIDwZN6rjgqLGGu7avXs9qhSEawU2fO/a45z8lsevFbXa81eiIfqNk2EP2ZSUd77x6S7GtLD2smXccdFq+8Ai5hE+PN0g1ERs133cho2up4+tYQXMNhiTfspCy8QsJPmQgfwWg4kaZKgN/sArs7Y7mRa1JLmXhfqYMHXOvrK2tcWh2jvw8jMJ9fjrHf7HNQ3wbbZ25r3ZVad4M=
jobs:
  include:
  - stage: Tests
    python: 3.6
    env:
    - TOXENV=py36
    install: &1
    - pip install tox numpy scipy scikit-learn matplotlib seaborn
    script: &2
    - tox
    - pip install git+https://github.com/chlorochrule/cknn
  - python: 3.7
    env:
    - TOXENV=py37
    install: *1
    script: *2
  - stage: Deploy
    python: 3.7
    install:
    - pip install sphinx sphinx_rtd_theme
    script:
    - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
      source ./deploy.sh'
