language: python
os: linux
dist: xenial
branches:
  only:
  - master
env: 
jobs:
  include:
  - stage: Tests
    python: 3.6
    env:
    - TOXENV=py36
    install: &1
    - pip install tox numpy scipy scikit-learn matplotlib seaborn
    script: &2
    - tox
    - pip install git+https://github.com/chlorochrule/cknn
  - python: 3.7
    env:
    - TOXENV=py37
    install: *1
    script: *2
  - stage: Deploy
    python: 3.7
    env:
    - secure: xMJY23zNB/FY6I4NdmpWTJtKOISpyMTAa0WTfkSnytWaRm9j0IqJy6NG6RYg/lYHIrR26hDH/Xu7RDi7ZGNxlYYgxOIiGa/Sj19vwP7wTgc+J2b5HyQlN739Uq7uEeLzDa861wF43I7BtRVcmyjte3D/45Y5MAuqQCIIxqpMUbxt+jLpHpLC4vEQZQUvpWOJF2/C2RY76vG3xzmG/Iq7JTSXTlfiaJE2faSUtae77z07/Nvf8GPNYAksy4b82xSj9R5x3hxinBV1MrnjDweFFSpUVi44TgQmY7He48JdzE2vG5MeZ6Jgk8lj2BbDfYF0TZ17Ji+sfGTtbizX4nk6NmGDDkn/T11UGhMBmbBqA5KTOwRYc54z9yCOMOQHG/eyMWoh7rHvdLWuB0+z4Ed1sDriLTGe2agXevIwvPAkSLjZss72SAz6Os+8dud4EsHtli26eOeBWH0G3HfLonaaf/AVuhOBLLQTVVfLelxY4XaUeZdLTt8MZfUrvccaZ33goaC+Uf/H2HV9YtbOZCTsFItXLmxixX9cp55qQub8cdBNsQ5i4W4GXm6UHaoHkc/lAhqcpIZZi2/KS1JphjedY5HM3fJLTGT36b5EFph2IKvaCvbiO1kaJUcp0jjHl1AaGpkGEDzJkAfGmLLGIUdo+a/p3NSDkT0/uIcFgSdGo1A=
    install:
    - pip install sphinx sphinx_rtd_theme
    script:
    - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && source ./deploy.sh'
